namespace Sconfig.Contracts.Configuration.Enums
{
    public enum ConfigurationGroupValidationCodes
    {
        INVALID_CONFIGURATION_GROUP_NAME,
        CONFIGURATION_GROUP_ALREADY_EXISTS,
        CONFIGURATION_GROUP_DOES_NOT_EXIST,
        INVALID_CONFIGURATION_GROUP_PROJECT,
        INVALID_CONFIGURATION_GROUP_APPLICATION,
        INVALID_CONFIGURATION_GROUP_PARENT
    }
}
